//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHSEntities : DbContext
    {
        public QLHSEntities()
            : base("name=QLHSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tb_Class> tb_Class { get; set; }
        public DbSet<tb_Groups> tb_Groups { get; set; }
        public DbSet<tb_Menu> tb_Menu { get; set; }
        public DbSet<tb_Regulations> tb_Regulations { get; set; }
        public DbSet<tb_Roles> tb_Roles { get; set; }
        public DbSet<tb_Semesters> tb_Semesters { get; set; }
        public DbSet<tb_Students> tb_Students { get; set; }
        public DbSet<tb_Subjects> tb_Subjects { get; set; }
        public DbSet<tb_TranScripts> tb_TranScripts { get; set; }
        public DbSet<tb_Users> tb_Users { get; set; }
    }
}
