//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Roles
    {
        public tb_Roles()
        {
            this.tb_Menu = new HashSet<tb_Menu>();
            this.tb_Users = new HashSet<tb_Users>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<tb_Menu> tb_Menu { get; set; }
        public virtual ICollection<tb_Users> tb_Users { get; set; }
    }
}
