//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Students
    {
        public tb_Students()
        {
            this.tb_TranScripts = new HashSet<tb_TranScripts>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tb_Class tb_Class { get; set; }
        public virtual ICollection<tb_TranScripts> tb_TranScripts { get; set; }
    }
}
