//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TranScripts
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<double> Grade15 { get; set; }
        public Nullable<double> Grade45 { get; set; }
        public Nullable<double> GradeSemester { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tb_Semesters tb_Semesters { get; set; }
        public virtual tb_Students tb_Students { get; set; }
        public virtual tb_Subjects tb_Subjects { get; set; }
    }
}
